config/routes.rb
Rails.application.routes.draw do
  root "home#index", to: "home#index"

  get 'carts/index'

  get 'admins/index', to: 'admins#index', as: :admins

  get 'home/product_modal', to: 'home#product_modal'
  get 'home/registro', to: 'home#registro', as: :registro
  post 'home/create', to: 'home#create_registro'
  get 'home/list_products', to: 'home#list_products', as: :list_products
  get 'home/carousel', to: 'home#carousel', as: :carousel
  get 'home/pre_login', to: 'home#pre_login', as: :pre_login
  get 'home/product_modal', to: 'home#product_modal', as: :product_modal
  post 'home/product_modal', to: 'home#orden', as: :orden
  
  get 'sessions/new', to: 'sessions#new', as: :login
  post 'sessions/create', to: 'sessions#create'
  
  resources :clientes
  
  resources :tiendas
  resources :productos
  resources :usuarios


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cliente.rb
class Cliente < ApplicationRecord
    has_many :ubicacions

    validates :nombre, presence: true, length: {minimum: 4}
    validates :telefono, presence: true, length: {minimum: 10}, numericality: { only_integer: true }, uniqueness: true
    validates :contraseña, presence: true, length: { in: 8..20 }, format: { with: /\A[a-zA-Z0-9!@#$%^&*]+\z/}
    validates :condiciones, acceptance: true

    def authenticate(contraseña)
        # Lógica para verificar si la contraseña proporcionada coincide con la contraseña almacenada
        # en la base de datos para este cliente. Por ejemplo:
        self.contraseña == contraseña
    end
end

app/models/producto.rb
class Producto < ApplicationRecord
    has_one_attached :foto
    validates :nombre, presence: true
    validates :precio, presence: true
    validates :descripcion, presence: true
    validates :promocion, presence: true
    validates :tipo, presence: true
end

app/models/tienda.rb
class Tienda < ApplicationRecord
end

app/models/ubicacion.rb
class Ubicacion < ApplicationRecord
  belongs_to :cliente
end

app/models/usuario.rb
class Usuario < ApplicationRecord
    validates :nombre, presence: true, length: {minimum: 4}
    validates :nombre, format: { with: /\A[a-zA-Z]+\z/}
    validates :correo, presence: true, uniqueness: true
    validates :contraseña, presence: true, length: { in: 8..20 }, format: { with: /\A[a-zA-Z0-9!@#$%^&*]+\z/}
    validates :roll, presence: true
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
  end
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  def index
    @clientes = Cliente.all
  end

  def show
    @cliente = Cliente.find(params[:id])
  end

  def new
    @cliente = Cliente.new
  end

  def create
    @cliente = Cliente.new(cliente_params)

    if @cliente.save
        redirect_to clientes_path
    else
        render :new, status: :unprocessable_entity
    end
  end

  def edit
    @cliente = Cliente.find(params[:id])
  end

  def update
    @cliente = Cliente.find(params[:id])

    if @cliente.update(cliente_params)
        redirect_to @cliente
    else
        render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @cliente = Cliente.find(params[:id])
    @cliente.destroy

    redirect_to clientes_path, status: :see_other
  end

  private

  def cliente_params
    params.require(:cliente).permit(:nombre, :telefono, :contraseña)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # http_basic_authenticate_with name: "cascady", password: "contraseña", except: [:index]

  def index
  end
  
  def list_products

    if params[:categoria].present?
      @productos = Producto.where(tipo: params[:categoria]).with_attached_foto
    else
      @productos = Producto.all.with_attached_foto
    end

    @in = Producto.where(id: 9)
  end

  def registro
  end

  def create_registro

    @cliente = Cliente.new(cliente_params)

    if @cliente.save
        redirect_to login_path
    else
        render :registro, status: :unprocessable_entity
    end

  end

  def pre_login
  end

  def carousel
  end

  def cliente_params
    params.require(:cliente).permit(:nombre, :telefono, :contraseña, :condiciones)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
  
    def create
      @Cliente = Cliente.find_by("telefono = :telefono", { telefono: params[:telefono] })
  
      if @Cliente&.authenticate(params[:contraseña])
        redirect_to list_products_path
      else
        redirect_to new_session_path
      end
    end
  end

app/controllers/tiendas_controller.rb
class TiendasController < ApplicationController
  def index
    @tiendas = Tienda.all
  end

  def show
    @tienda = Tienda.find(params[:id])
  end

  def new
    @tienda = Tienda.new
  end

  def create
    @tienda = Tienda.new(tienda_params)

    if @tienda.save
        redirect_to tiendas_path, notice: 'Se ha agregado un nuevo tienda'
    else
        render :new, status: :unprocessable_entity
    end
  end

  def edit
    @tienda = Tienda.find(params[:id])
  end

  def update
    @tienda = Tienda.find(params[:id])

    if @tienda.update(tienda_params)
        redirect_to @tienda
    else
        render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @tienda = Tienda.find(params[:id])
    @tienda.destroy

    redirect_to tiendas_path, status: :see_other
  end

  private

  def tienda_params
    params.require(:tienda).permit(:nombre, :direccion, :telefono)
  end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  def index
    @usuarios = Usuario.all
  end

  def show
    @usuario = Usuario.find(params[:id])
  end

  def new
    @usuario = Usuario.new
  end

  def create
    @usuario = Usuario.new(usuario_params)

    if @usuario.save
        redirect_to usuarios_path
    else
        render :new, status: :unprocessable_entity
    end
  end

  def edit
    @usuario = Usuario.find(params[:id])
  end

  def update
    @usuario = Usuario.find(params[:id])

    if @usuario.update(usuario_params)
        redirect_to @usuario
    else
        render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @usuario = Usuario.find(params[:id])
    @usuario.destroy

    redirect_to usuarios_path, status: :see_other
  end

  private

  def usuario_params
    params.require(:usuario).permit(:nombre, :correo, :contraseña, :roll)
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/platillos_helper.rb
module PlatillosHelper
end

app/helpers/tiendas_helper.rb
module TiendasHelper
end

app/helpers/ubicacions_helper.rb
module UbicacionsHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/clientes/edit.html.erb
<body>
    <nav class="bg-white grid grid-cols-12 flex-row content-center min-[320px]:h-8 sm:h-10 md:h-12 2xl:h-[52px]">
        <div class="flex flex-row place-items-center space-x-2 col-span-5 min-[320px]:ml-2 sm:ml-3 md:ml-4 lg:ml-5 xl:ml-6 2xl:ml-7">
            <a href="<%=cliente_path(@cliente)%>">
                <svg class="fill-[#6B6A6F] min-[320px]:w-[10px] min-[320px]:h-[10px] sm:w-4 sm:h-4 md:w-[18px] md:h-[18px] xl:w-5 xl:h-5 2xl:w-[22px] 2xl:h-[22px]" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M9.4 233.4c-12.5 12.5-12.5 32.8 0 45.3l160 160c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L109.2 288 416 288c17.7 0 32-14.3 32-32s-14.3-32-32-32l-306.7 0L214.6 118.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0l-160 160z"/></svg>
            </a>
            <a href="<%=cliente_path(@cliente)%>">
                <p class="font-ubuntu font-bold text-[#6B6A6F] min-[320px]:text-[10px] sm:text-[12px] md:text-[14px] xl:text-[16px] 2xl:text-[18px]">Volver</p>
            </a>
        </div>
    </nav>
    <div class="container mx-auto w-5/6">
        <div class="flex-auto min-[320px]:mt-6 min-[320px]:mb-4 sm:mt-9 sm:mb-6 md:mt-12 md:mb-8">
            <h1 class="text-center font-ubuntu font-bold min-[320px]:text-[16px] sm:text-[20px] md:text-[22px] lg:text-[24px] 2xl:text-[28px]">Editar datos de cliente</h1>
        </div>
        <%= render "form", cliente: @cliente %>
    </div>
</body>

app/views/clientes/index.html.erb
<body>
    <nav class="bg-white grid grid-cols-12 flex-row content-center min-[320px]:h-8 sm:h-10 md:h-12 2xl:h-[52px]">
        <div class="flex flex-row place-items-center space-x-2 col-span-5 min-[320px]:ml-2 sm:ml-3 md:ml-4 lg:ml-5 xl:ml-6 2xl:ml-7">
            <a href="<%=admins_path%>">
                <svg class="fill-[#6B6A6F] min-[320px]:w-[10px] min-[320px]:h-[10px] sm:w-4 sm:h-4 md:w-[18px] md:h-[18px] xl:w-5 xl:h-5 2xl:w-[22px] 2xl:h-[22px]" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M9.4 233.4c-12.5 12.5-12.5 32.8 0 45.3l160 160c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L109.2 288 416 288c17.7 0 32-14.3 32-32s-14.3-32-32-32l-306.7 0L214.6 118.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0l-160 160z"/></svg>
            </a>
            <a href="<%=admins_path%>">
                <p class="font-ubuntu font-bold text-[#6B6A6F] min-[320px]:text-[10px] sm:text-[12px] md:text-[14px] xl:text-[16px] 2xl:text-[18px]">Volver</p>
            </a>
        </div>
    </nav>
    <div class="flex place-content-center place-items-center min-[320px]:mt-6 min-[320px]:mb-4 sm:mt-9 sm:mb-6 md:mt-12 md:mb-8">
        <h1 class="font-ubuntu font-bold min-[320px]:text-[16px] sm:text-[20px] md:text-[22px] lg:text-[24px] 2xl:text-[28px]">Clientes</h1>
    </div>
    <div class="row-auto">
        <div class="flex justify-center">
            <a href="<%=new_cliente_path%>" class=" justify-center w-4/5 px-4 py-2 font-ubuntu inline-block text-center bg-[#50BC00] text-white hover:bg-[#58AB00] hover:text-white font-bold py-2 px-4 rounded min-[320px]:h-6 sm:h-[30px] md:h-9 xl:h-10 2xl:h-11">
                Agregar cliente
            </a>
    </div>
    <br>

    <div class="flex justify-center">
        
        <table class="table-fixed bg-gray rounded-lg w-4/5">
            <thead>
                <tr>
                    <th class="text-left px-4 py-2 bg-gray-200 text-gray-600">Nombre</th>
                    <th class="text-left px-4 py-2 bg-gray-200 text-gray-600">Telefono</th>
                </tr>
            </thead>
            <tbody>
                <% @clientes.each do |cliente|%>
                        <tr onclick="window.location.href='<%= cliente_path(cliente.id) %>'" style="cursor: pointer;" class="hover:bg-gray-100">
                            <td class="text-left px-4 py-2"><%=cliente.nombre %></td>
                            <td class="text-left px-4 py-2"><%=cliente.telefono %></td>
                        </tr>
                <%end%>
            </tbody>
        </table>
    </div>
</body>

app/views/clientes/show.html.erb
<body>
    <nav class="bg-white grid grid-cols-12 flex-row content-center min-[320px]:h-8 sm:h-10 md:h-12 2xl:h-[52px]">
        <div class="flex flex-row place-items-center space-x-2 col-span-5 min-[320px]:ml-2 sm:ml-3 md:ml-4 lg:ml-5 xl:ml-6 2xl:ml-7">
            <a href="<%=clientes_path%>">
                <svg class="fill-[#6B6A6F] min-[320px]:w-[10px] min-[320px]:h-[10px] sm:w-4 sm:h-4 md:w-[18px] md:h-[18px] xl:w-5 xl:h-5 2xl:w-[22px] 2xl:h-[22px]" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M9.4 233.4c-12.5 12.5-12.5 32.8 0 45.3l160 160c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L109.2 288 416 288c17.7 0 32-14.3 32-32s-14.3-32-32-32l-306.7 0L214.6 118.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0l-160 160z"/></svg>
            </a>
            <a href="<%=clientes_path%>">
                <p class="font-ubuntu font-bold text-[#6B6A6F] min-[320px]:text-[10px] sm:text-[12px] md:text-[14px] xl:text-[16px] 2xl:text-[18px]">Volver</p>
            </a>
        </div>
    </nav>

    <div>
        <div class="flex place-content-center place-items-center min-[320px]:mt-6 min-[320px]:mb-4 sm:mt-9 sm:mb-6 md:mt-12 md:mb-8">
            <h1 class="font-ubuntu font-bold min-[320px]:text-[16px] sm:text-[20px] md:text-[22px] lg:text-[24px] 2xl:text-[28px]">Informacion del cliente</h1>
        </div>
    </div>
    <div class="container mx-auto">
        <div class="max-w-md mx-auto bg-white shadow-lg rounded-lg overflow-hidden">
            <div class="px-4 py-2">
                <h2 class="text-lg font-semibold text-gray-800">Datos</h2>
                <p class="text-sm text-gray-600 mt-1">Aquí están los detalles del cliente:</p>
            </div>
            <div class="px-4 py-2">
                <p class="text-sm text-gray-600">Nombre: <%=@cliente.nombre%></p>
                <p class="text-sm text-gray-600">Teléfono: <%=@cliente.telefono%></p>
                <p class="text-sm text-gray-600">Contraseña: <%=@cliente.contraseña%></p>
            </div>
            <hr>
            <div class="flex">
                <div class="flex-auto py-2 px-4">
                    <a href="<%=edit_cliente_path(@cliente)%>" class="inline-block bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded flex items-center justify-center">Editar</a>
                </div>
                <div class="flex-auto py-2 px-4">
                    <%= link_to "Eliminar", cliente_path(@cliente), class:"inline-block bg-[#FF1F1F] hover:bg-[#AB0000] text-white font-bold py-2 px-4 rounded flex items-center justify-center", data: {
                        turbo_method: :delete,
                        turbo_confirm: "Estas seguro de eliminar el cliente ?"
                    } %>
                </div>
            </div>
        </div> 
    </div>
</body>

app/views/tiendas/index.html.erb
<body>
    <nav class="bg-white grid grid-cols-12 flex-row content-center min-[320px]:h-8 sm:h-10 md:h-12 2xl:h-[52px]">
        <div class="flex flex-row place-items-center space-x-2 col-span-5 min-[320px]:ml-2 sm:ml-3 md:ml-4 lg:ml-5 xl:ml-6 2xl:ml-7">
            <a href="<%=admins_path%>">
                <svg class="fill-[#6B6A6F] min-[320px]:w-[10px] min-[320px]:h-[10px] sm:w-4 sm:h-4 md:w-[18px] md:h-[18px] xl:w-5 xl:h-5 2xl:w-[22px] 2xl:h-[22px]" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M9.4 233.4c-12.5 12.5-12.5 32.8 0 45.3l160 160c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L109.2 288 416 288c17.7 0 32-14.3 32-32s-14.3-32-32-32l-306.7 0L214.6 118.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0l-160 160z"/></svg>
            </a>
            <a href="<%=admins_path%>">
                <p class="font-ubuntu font-bold text-[#6B6A6F] min-[320px]:text-[10px] sm:text-[12px] md:text-[14px] xl:text-[16px] 2xl:text-[18px]">Volver</p>
            </a>
        </div>
    </nav>
    <div class="flex place-content-center place-items-center min-[320px]:mt-6 min-[320px]:mb-4 sm:mt-9 sm:mb-6 md:mt-12 md:mb-8">
        <h1 class="font-ubuntu font-bold min-[320px]:text-[16px] sm:text-[20px] md:text-[22px] lg:text-[24px] 2xl:text-[28px]">Tiendas</h1>
    </div>    
    </div>
        <div class="row-auto">
            <div class="flex justify-center">
                <a href="<%=new_tienda_path%>" class=" justify-center w-4/5 px-4 py-2 font-ubuntu inline-block text-center bg-[#50BC00] text-white hover:bg-[#58AB00] hover:text-white font-bold py-2 px-4 rounded min-[320px]:h-6 sm:h-[30px] md:h-9 xl:h-10 2xl:h-11">
                    Agregar tienda
                </a>
        </div>
    <br>

    <div class="flex justify-center">
        <table class="table-fixed bg-gray rounded-lg w-4/5">
            <thead>
                <tr>
                    <th class="text-left px-4 py-2 bg-gray-200 text-gray-600">Nombre</th>
                    <th class="text-left px-4 py-2 bg-gray-200 text-gray-600">Dirección</th>
                </tr>
            </thead>
            <tbody>
                <% @tiendas.each do |tienda|%>
                        <tr onclick="window.location.href='<%= tienda_path(tienda.id) %>'" style="cursor: pointer;" class="hover:bg-gray-100">
                            <td class="text-left px-4 py-2"><%=tienda.nombre %></td>
                            <td class="text-left px-4 py-2"><%=tienda.direccion %></td>
                        </tr>
                <%end%>
            </tbody>
        </table>
    </div>
</body>

app/views/tiendas/show.html.erb
<body>
    <nav class="bg-white grid grid-cols-12 flex-row content-center min-[320px]:h-8 sm:h-10 md:h-12 2xl:h-[52px]">
        <div class="flex flex-row place-items-center space-x-2 col-span-5 min-[320px]:ml-2 sm:ml-3 md:ml-4 lg:ml-5 xl:ml-6 2xl:ml-7">
            <a href="<%=tiendas_path%>">
                <svg class="fill-[#6B6A6F] min-[320px]:w-[10px] min-[320px]:h-[10px] sm:w-4 sm:h-4 md:w-[18px] md:h-[18px] xl:w-5 xl:h-5 2xl:w-[22px] 2xl:h-[22px]" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M9.4 233.4c-12.5 12.5-12.5 32.8 0 45.3l160 160c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L109.2 288 416 288c17.7 0 32-14.3 32-32s-14.3-32-32-32l-306.7 0L214.6 118.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0l-160 160z"/></svg>
            </a>
            <a href="<%=tiendas_path%>">
                <p class="font-ubuntu font-bold text-[#6B6A6F] min-[320px]:text-[10px] sm:text-[12px] md:text-[14px] xl:text-[16px] 2xl:text-[18px]">Volver</p>
            </a>
        </div>
    </nav>

    <div>
        <div class="flex place-content-center place-items-center min-[320px]:mt-6 min-[320px]:mb-4 sm:mt-9 sm:mb-6 md:mt-12 md:mb-8">
            <h1 class="font-ubuntu font-bold min-[320px]:text-[16px] sm:text-[20px] md:text-[22px] lg:text-[24px] 2xl:text-[28px]">Informacion de tienda</h1>
        </div>
    </div>
    <div class="container mx-auto">
        <div class="max-w-md mx-auto bg-white shadow-lg rounded-lg overflow-hidden">
            <div class="px-4 py-2">
                <h2 class="text-lg font-semibold text-gray-800">Datos</h2>
                <p class="text-sm text-gray-600 mt-1">Aquí están los detalles del tienda:</p>
            </div>
            <div class="px-4 py-2">
                <p class="text-sm text-gray-600">Nombre: <%=@tienda.nombre%></p>
                <p class="text-sm text-gray-600">Teléfono: <%=@tienda.telefono%></p>
                <p class="text-sm text-gray-600">Dirección: <%=@tienda.direccion%></p>
            </div>
            <hr>
            <div class="flex">
                <div class="flex-auto py-2 px-4">
                    <a href="<%=edit_tienda_path(@tienda)%>" class="inline-block bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded flex items-center justify-center">Editar</a>
                </div>
                <div class="flex-auto py-2 px-4">
                    <%= link_to "Eliminar", tienda_path(@tienda), class:"inline-block bg-[#FF1F1F] hover:bg-[#AB0000] text-white font-bold py-2 px-4 rounded flex items-center justify-center", data: {
                        turbo_method: :delete,
                        turbo_confirm: "Estas seguro de eliminar el cliente ?"
                    } %>
                </div>
            </div>
        </div> 
    </div>
</body>

app/views/usuarios/index.html.erb
<body>
    <nav class="bg-white grid grid-cols-12 flex-row content-center min-[320px]:h-8 sm:h-10 md:h-12 2xl:h-[52px]">
        <div class="flex flex-row place-items-center space-x-2 col-span-5 min-[320px]:ml-2 sm:ml-3 md:ml-4 lg:ml-5 xl:ml-6 2xl:ml-7">
            <a href="<%=admins_path%>">
                <svg class="fill-[#6B6A6F] min-[320px]:w-[10px] min-[320px]:h-[10px] sm:w-4 sm:h-4 md:w-[18px] md:h-[18px] xl:w-5 xl:h-5 2xl:w-[22px] 2xl:h-[22px]" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M9.4 233.4c-12.5 12.5-12.5 32.8 0 45.3l160 160c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L109.2 288 416 288c17.7 0 32-14.3 32-32s-14.3-32-32-32l-306.7 0L214.6 118.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0l-160 160z"/></svg>
            </a>
            <a href="<%=admins_path%>">
                <p class="font-ubuntu font-bold text-[#6B6A6F] min-[320px]:text-[10px] sm:text-[12px] md:text-[14px] xl:text-[16px] 2xl:text-[18px]">Volver</p>
            </a>
        </div>
    </nav>
    <div class="flex place-content-center place-items-center min-[320px]:mt-6 min-[320px]:mb-4 sm:mt-9 sm:mb-6 md:mt-12 md:mb-8">
        <h1 class="font-ubuntu font-bold min-[320px]:text-[16px] sm:text-[20px] md:text-[22px] lg:text-[24px] 2xl:text-[28px]">Usuarios</h1>
    </div>    
    </div>
        <div class="row-auto">
            <div class="flex justify-center">
                <a href="<%=new_usuario_path%>" class=" justify-center w-4/5 px-4 py-2 font-ubuntu inline-block text-center bg-[#50BC00] text-white hover:bg-[#58AB00] hover:text-white font-bold py-2 px-4 rounded min-[320px]:h-6 sm:h-[30px] md:h-9 xl:h-10 2xl:h-11">
                    Agregar usuario
                </a>
        </div>
    <br>

    <div class="flex justify-center">
        <table class="table-fixed bg-gray rounded-lg w-4/5">
            <thead>
                <tr>
                    <th class="text-left px-4 py-2 bg-gray-200 text-gray-600">Nombre</th>
                    <th class="text-left px-4 py-2 bg-gray-200 text-gray-600">Correo</th>
                </tr>
            </thead>
            <tbody>
                <% @usuarios.each do |usuario|%>
                        <tr onclick="window.location.href='<%= usuario_path(usuario.id) %>'" style="cursor: pointer;" class="hover:bg-gray-100">
                            <td class="text-left px-4 py-2"><%=usuario.nombre %></td>
                            <td class="text-left px-4 py-2"><%=usuario.correo %></td>
                        </tr>
                <%end%>
            </tbody>
        </table>
    </div>
</body>