config/routes.rb
Rails.application.routes.draw do
  root "home#index", to: "home#index"

  get 'carts/index'

  get 'admins/index', to: 'admins#index', as: :admins

  get 'home/product_modal', to: 'home#product_modal'
  get 'home/registro', to: 'home#registro', as: :registro
  post 'home/create', to: 'home#create_registro'
  get 'home/list_products', to: 'home#list_products', as: :list_products
  get 'home/carousel', to: 'home#carousel', as: :carousel
  get 'home/pre_login', to: 'home#pre_login', as: :pre_login
  get 'home/product_modal', to: 'home#product_modal', as: :product_modal
  post 'home/product_modal', to: 'home#orden', as: :orden
  
  get 'sessions/new', to: 'sessions#new', as: :login
  post 'sessions/create', to: 'sessions#create'
  
  resources :clientes
  
  resources :tiendas
  resources :productos
  resources :usuarios


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cliente.rb
class Cliente < ApplicationRecord
    has_many :ubicacions

    validates :nombre, presence: true, length: {minimum: 4}
    validates :telefono, presence: true, length: {minimum: 10}, numericality: { only_integer: true }, uniqueness: true
    validates :contraseña, presence: true, length: { in: 8..20 }, format: { with: /\A[a-zA-Z0-9!@#$%^&*]+\z/}
    validates :condiciones, acceptance: true

    def authenticate(contraseña)
        # Lógica para verificar si la contraseña proporcionada coincide con la contraseña almacenada
        # en la base de datos para este cliente. Por ejemplo:
        self.contraseña == contraseña
    end
end

app/models/producto.rb
class Producto < ApplicationRecord
    has_one_attached :foto
    validates :nombre, presence: true
    validates :precio, presence: true
    validates :descripcion, presence: true
    validates :promocion, presence: true
    validates :tipo, presence: true
end

app/models/tienda.rb
class Tienda < ApplicationRecord
end

app/models/ubicacion.rb
class Ubicacion < ApplicationRecord
  belongs_to :cliente
end

app/models/usuario.rb
class Usuario < ApplicationRecord
    validates :nombre, presence: true, length: {minimum: 4}
    validates :nombre, format: { with: /\A[a-zA-Z]+\z/}
    validates :correo, presence: true, uniqueness: true
    validates :contraseña, presence: true, length: { in: 8..20 }, format: { with: /\A[a-zA-Z0-9!@#$%^&*]+\z/}
    validates :roll, presence: true
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # http_basic_authenticate_with name: "cascady", password: "contraseña", except: [:index]

  def index
  end
  
  def list_products

    if params[:categoria].present?
      @productos = Producto.where(tipo: params[:categoria]).with_attached_foto
    else
      @productos = Producto.all.with_attached_foto
    end

    @in = Producto.where(id: 9)
  end

  def registro
  end

  def create_registro

    @cliente = Cliente.new(cliente_params)

    if @cliente.save
        redirect_to login_path
    else
        render :registro, status: :unprocessable_entity
    end

  end

  def pre_login
  end

  def carousel
  end

  def cliente_params
    params.require(:cliente).permit(:nombre, :telefono, :contraseña, :condiciones)
  end
end

app/controllers/tiendas_controller.rb
class TiendasController < ApplicationController
  def index
    @tiendas = Tienda.all
  end

  def show
    @tienda = Tienda.find(params[:id])
  end

  def new
    @tienda = Tienda.new
  end

  def create
    @tienda = Tienda.new(tienda_params)

    if @tienda.save
        redirect_to tiendas_path, notice: 'Se ha agregado un nuevo tienda'
    else
        render :new, status: :unprocessable_entity
    end
  end

  def edit
    @tienda = Tienda.find(params[:id])
  end

  def update
    @tienda = Tienda.find(params[:id])

    if @tienda.update(tienda_params)
        redirect_to @tienda
    else
        render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @tienda = Tienda.find(params[:id])
    @tienda.destroy

    redirect_to tiendas_path, status: :see_other
  end

  private

  def tienda_params
    params.require(:tienda).permit(:nombre, :direccion, :telefono)
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/platillos_helper.rb
module PlatillosHelper
end

app/helpers/tiendas_helper.rb
module TiendasHelper
end

app/helpers/ubicacions_helper.rb
module UbicacionsHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/admins/index.html.erb
<body>
    <nav class="bg-white grid grid-cols-12 flex-row content-center min-[320px]:h-8 sm:h-10 md:h-12 2xl:h-[52px]">
        <div class="flex flex-row place-items-center space-x-2 col-span-5 min-[320px]:ml-2 sm:ml-3 md:ml-4 lg:ml-5 xl:ml-6 2xl:ml-7">
            <a href="<%=root_path%>">
                <svg class="fill-[#6B6A6F] min-[320px]:w-[10px] min-[320px]:h-[10px] sm:w-4 sm:h-4 md:w-[18px] md:h-[18px] xl:w-5 xl:h-5 2xl:w-[22px] 2xl:h-[22px]" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M9.4 233.4c-12.5 12.5-12.5 32.8 0 45.3l160 160c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L109.2 288 416 288c17.7 0 32-14.3 32-32s-14.3-32-32-32l-306.7 0L214.6 118.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0l-160 160z"/></svg>
            </a>
            <a href="<%=root_path%>">
                <p class="font-ubuntu font-bold text-[#6B6A6F] min-[320px]:text-[10px] sm:text-[12px] md:text-[14px] xl:text-[16px] 2xl:text-[18px]">Volver</p>
            </a>
        </div>
    </nav>
    <div class="lg:grid lg:grid-cols-12 h-screen ">
        <div class="flex flex-col lg:col-span-12">
            <div class="flex place-content-center place-items-center min-[320px]:mt-6 min-[320px]:mb-4 sm:mt-9 sm:mb-6 md:mt-12 md:mb-8">
                <h1 class="font-ubuntu font-bold min-[320px]:text-[16px] sm:text-[20px] md:text-[22px] lg:text-[24px] 2xl:text-[28px]">Administrador</h1>
            </div>
            <div class="flex flex-col min-[320px]:mx-[40px] min-[320px]:space-y-4 min-[320px]:mb-4 sm:mx-[110px] sm:space-y-6 sm:mb-6 md:mx-[160px] md:mb-8 lg:mx-16 xl:mx-[106px] 2xl:mx-[128px]">
                <div class="flex flex-col space-y-1">
                    <a href="<%=clientes_path%>" class="font-ubuntu inline-block text-center bg-white border border-red-500 text-red-500 hover:bg-red-500 hover:text-white hover:border-red-700 font-bold py-2 px-4 rounded min-[320px]:h-6 sm:h-[30px] md:h-9 xl:h-10 2xl:h-11">
                        Clientes
                    </a>
                </div>
                <div class="flex flex-col space-y-1">
                    <a href="<%=productos_path%>" class="font-ubuntu inline-block text-center bg-white border border-red-500 text-red-500 hover:bg-red-500 hover:text-white hover:border-red-700 font-bold py-2 px-4 rounded min-[320px]:h-6 sm:h-[30px] md:h-9 xl:h-10 2xl:h-11">
                        Productos
                    </a>
                </div>
                <div class="flex flex-col space-y-1">
                    <a href="<%=tiendas_path%>" class="font-ubuntu inline-block text-center bg-white border border-red-500 text-red-500 hover:bg-red-500 hover:text-white hover:border-red-700 font-bold py-2 px-4 rounded min-[320px]:h-6 sm:h-[30px] md:h-9 xl:h-10 2xl:h-11">
                        Tiendas
                    </a>
                </div>
                <div class="flex flex-col space-y-1">
                    <a href="<%=usuarios_path%>" class="font-ubuntu inline-block text-center bg-white border border-red-500 text-red-500 hover:bg-red-500 hover:text-white hover:border-red-700 font-bold py-2 px-4 rounded min-[320px]:h-6 sm:h-[30px] md:h-9 xl:h-10 2xl:h-11">
                        Usuarios
                    </a>
                </div>
            </div>
        </div>
    </div>
</body>

app/views/shared/_footer.html.erb
<footer class="bg-[#FFFFFF] bottom-0">
    <div class="min-[320px]:pb-3 min-[320px]:text-center min-[320px]:mt-2 sm:p-4 sm:flex sm:flex-row sm:justify-between sm:text-left sm:mt-3 md:p-5 md:mt-4 lg:p-6 lg:mt-5 xl:p-7 xl:mt-6 2xl:p-8 2xl:mt-7">
        <div class="min-[320px]:py-2 sm:p-0 md:p-0 lg:p-0 xl:p-0 2xl:p-0">
            <div>
                <p class="font-ubuntu font-medium min-[320px]:text-[12px] min-[320px]:pb-1 sm:text-[14px] sm:pb-2 md:text-[14px] md:pb-3 lg:pb-3 lg:text-[16px] xl:pb-3 xl:text-[16px] 2xl:pb-[14px] 2xl:text-[18px]">Sobre Cascady</p>
            </div>
            <div class="font-ubuntu font-light min-[320px]:text-[10px] sm:text-[12px] md:text-[12px] lg:text-[14px] xl:text-[14px] 2xl:text-[16px]">
                <p class="min-[320px]:pb-1 sm:pb-[6px] md:pb-2 lg:pb-2 xl:pb-[10px] 2xl:pb-3">Términos y condiciones</p>
                <p class="min-[320px]:pb-1 sm:pb-[6px] md:pb-2 lg:pb-2 xl:pb-[10px] 2xl:pb-3">Políticas de privacidad</p>
                <p class="min-[320px]:pb-1 sm:pb-[6px] md:pb-2 lg:pb-2 xl:pb-[10px] 2xl:pb-3">Contactos</p>
                <p>Redes</p>
            </div>
        </div>
        <div class="min-[320px]:pb-2 sm:p-0 md:p-0 lg:p-0 xl:p-0 2xl:p-0">
            <div>
                <p class="font-ubuntu font-medium min-[320px]:text-[12px] min-[320px]:pb-1 sm:text-[14px] sm:pb-2 md:text-[14px] md:pb-3 lg:pb-3 lg:text-[16px] xl:pb-3 xl:text-[16px] 2xl:pb-[14px] 2xl:text-[18px]">Categorías</p>
            </div>
            <div class="font-ubuntu font-light min-[320px]:text-[10px] sm:text-[12px] md:text-[12px] lg:text-[14px] xl:text-[14px] 2xl:text-[16px]">
                <p class="min-[320px]:pb-1 sm:pb-[6px] md:pb-2 lg:pb-2 xl:pb-[10px] 2xl:pb-3"><a href="<%=admins_path%>" >Empleados</a></p>
                <p class="min-[320px]:pb-1 sm:pb-[6px] md:pb-2 lg:pb-2 xl:pb-[10px] 2xl:pb-3">Catalógo de productos</p>
                <p class="min-[320px]:pb-1 sm:pb-[6px] md:pb-2 lg:pb-2 xl:pb-[10px] 2xl:pb-3">Locales cerca de mí</p>
                <p class="min-[320px]:pb-1 sm:pb-[6px] md:pb-2 lg:pb-2 xl:pb-[10px] 2xl:pb-3">Promociones y ofertas</p>
            </div>
        </div>
        <div>
            <div>
                <p class="font-ubuntu font-medium min-[320px]:text-[12px] min-[320px]:pb-1 sm:text-[14px] sm:pb-2 md:text-[14px] md:pb-3 lg:pb-3 lg:text-[16px] xl:pb-3 xl:text-[16px] 2xl:pb-[14px] 2xl:text-[18px]">Únete con nosotros</p>
            </div>
            <div class="font-ubuntu font-light min-[320px]:text-[10px] sm:text-[12px] md:text-[12px] lg:text-[14px] xl:text-[14px] 2xl:text-[16px]">
                <p class="min-[320px]:pb-1 sm:pb-[6px] md:pb-2 lg:pb-2 xl:pb-[10px] 2xl:pb-3">Trabaja con nosotros</p>
                <p class="min-[320px]:pb-1 sm:pb-[6px] md:pb-2 lg:pb-2 xl:pb-[10px] 2xl:pb-3">Puestos disponibles</p>
            </div>
        </div>
    </div>
    <div class="flex flex-row justify-between items-center min-[320px]:px-2 min-[320px]:pb-2 sm:px-4 sm:pb-4 md:px-5 md:pb-5 lg:px-6 lg:pb-6 xl:px-7 xl:pb-7 2xl:px-8 2xl:pb-8">
            <div class="flex flex-row">
                <svg class="min-[320px]:w[14px] min-[320px]:h-[14px] min-[320px]:mr-1 sm:w-[18px] sm:h-[18px] sm:mr-2 md:w-[20px] md:h-[20px] md:mr-3 lg:w-[20px] lg:h-[20px] lg:mr-3 xl:w-[22px] xl:h-[22px] xl:mr-3 2xl:w-[24px] 2xl:h-[24px] 2xl:mr-[14px]" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><!--!Font Awesome Free 6.5.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path fill="#000000" d="M64 32C28.7 32 0 60.7 0 96V416c0 35.3 28.7 64 64 64h98.2V334.2H109.4V256h52.8V222.3c0-87.1 39.4-127.5 125-127.5c16.2 0 44.2 3.2 55.7 6.4V172c-6-.6-16.5-1-29.6-1c-42 0-58.2 15.9-58.2 57.2V256h83.6l-14.4 78.2H255V480H384c35.3 0 64-28.7 64-64V96c0-35.3-28.7-64-64-64H64z"/></svg>
                <svg class="min-[320px]:w[14px] min-[320px]:h-[14px] min-[320px]:mr-1 sm:w-[18px] sm:h-[18px] sm:mr-2 md:w-[20px] md:h-[20px] md:mr-3 lg:w-[20px] lg:h-[20px] lg:mr-3 xl:w-[22px] xl:h-[22px] xl:mr-3 2xl:w-[24px] 2xl:h-[24px] 2xl:mr-[14px]" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><!--!Font Awesome Free 6.5.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path fill="#000000" d="M224.1 141c-63.6 0-114.9 51.3-114.9 114.9s51.3 114.9 114.9 114.9S339 319.5 339 255.9 287.7 141 224.1 141zm0 189.6c-41.1 0-74.7-33.5-74.7-74.7s33.5-74.7 74.7-74.7 74.7 33.5 74.7 74.7-33.6 74.7-74.7 74.7zm146.4-194.3c0 14.9-12 26.8-26.8 26.8-14.9 0-26.8-12-26.8-26.8s12-26.8 26.8-26.8 26.8 12 26.8 26.8zm76.1 27.2c-1.7-35.9-9.9-67.7-36.2-93.9-26.2-26.2-58-34.4-93.9-36.2-37-2.1-147.9-2.1-184.9 0-35.8 1.7-67.6 9.9-93.9 36.1s-34.4 58-36.2 93.9c-2.1 37-2.1 147.9 0 184.9 1.7 35.9 9.9 67.7 36.2 93.9s58 34.4 93.9 36.2c37 2.1 147.9 2.1 184.9 0 35.9-1.7 67.7-9.9 93.9-36.2 26.2-26.2 34.4-58 36.2-93.9 2.1-37 2.1-147.8 0-184.8zM398.8 388c-7.8 19.6-22.9 34.7-42.6 42.6-29.5 11.7-99.5 9-132.1 9s-102.7 2.6-132.1-9c-19.6-7.8-34.7-22.9-42.6-42.6-11.7-29.5-9-99.5-9-132.1s-2.6-102.7 9-132.1c7.8-19.6 22.9-34.7 42.6-42.6 29.5-11.7 99.5-9 132.1-9s102.7-2.6 132.1 9c19.6 7.8 34.7 22.9 42.6 42.6 11.7 29.5 9 99.5 9 132.1s2.7 102.7-9 132.1z"/></svg>
                <svg class="min-[320px]:w[14px] min-[320px]:h-[14px] min-[320px]:mr-1 sm:w-[18px] sm:h-[18px] sm:mr-2 md:w-[20px] md:h-[20px] md:mr-3 lg:w-[20px] lg:h-[20px] lg:mr-3 xl:w-[22px] xl:h-[22px] xl:mr-3 2xl:w-[24px] 2xl:h-[24px] 2xl:mr-[14px]" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--!Font Awesome Free 6.5.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path fill="#000000" d="M389.2 48h70.6L305.6 224.2 487 464H345L233.7 318.6 106.5 464H35.8L200.7 275.5 26.8 48H172.4L272.9 180.9 389.2 48zM364.4 421.8h39.1L151.1 88h-42L364.4 421.8z"/></svg>

            </div>
            <div>
                <p class="min-[320px]:text-[8px] sm:text-[10px] md:text-[10px] lg:text-[12px] xl:text-[12px] 2xl:text-[14px]">© 2024 Cascady. All rights reserved.</p>
            </div>
        </div>
</footer>

app/views/shared/_navbar1.html.erb
<div class="bg-[#FFFFFF] flex flex-row items-center justify-between border-b border-[#6B6A6F] border-solid min-[320px]:h-8 sm:h-10 md:h-[48px] lg:h-[48px] xl:h-[48px] 2xl:h-[52px]">
    <div class="min-[320px]:px-2 sm:hidden">
        <div><svg class="fill-[#6B6A6F] hover:fill-[#929197] hover:duration-700 w-[18px] h-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M0 96C0 78.3 14.3 64 32 64H416c17.7 0 32 14.3 32 32s-14.3 32-32 32H32C14.3 128 0 113.7 0 96zM0 256c0-17.7 14.3-32 32-32H416c17.7 0 32 14.3 32 32s-14.3 32-32 32H32c-17.7 0-32-14.3-32-32zM448 416c0 17.7-14.3 32-32 32H32c-17.7 0-32-14.3-32-32s14.3-32 32-32H416c17.7 0 32 14.3 32 32z"/></svg></div>
    </div>
    <div class="py-1 sm:px-3 md:px-4 lg:px-5 xl:px-6 2xl:px-7">
        <%= link_to root_path, class:"flex justify-center" do %>
            <img class="min-[320px]:w-6 min-[320px]:h-6 sm:w-8 sm:h-8 md:w-[38px] md:h-[38px] lg:w-[38px] lg:h-[38px] xl:w-[38px] xl:h-[38px] 2xl:w-10 2xl:h-10" src="<%= asset_path("cascady.svg")%>" alt="logo">
        <%end%>
    </div>
    <div class="items-center font-ubuntu font-bold flex flex-row min-[320px]:hidden sm:flex sm:text-[12px] sm:space-x-[28px] md:text-[12px] md:space-x-[28px] lg:text-[14px] lg:space-x-[32px] xl:text-[14px] xl:space-x-[40px] 2xl:text-[16px] 2xl:space-x-[40px]">
        <div class="flex items-center border-r border-[#6B6A6F] sm:h-[14px] md:h-[14px] lg:h-4 xl:h-4 2xl:h-[18px]"><p class="hover:text-[#17A25F] hover:duration-300 sm:mr-7 md:mr-7 lg:mr-8 xl:mr-10 2xl:mr-10">Locales</p></div>
        <div class="flex items-center border-r border-[#6B6A6F] sm:h-[14px] md:h-[14px] lg:h-4 xl:h-4 2xl:h-[18px]"><p class="hover:text-[#17A25F] hover:duration-300 sm:mr-7 md:mr-7 lg:mr-8 xl:mr-10 2xl:mr-10">Sugerencias</p></div>
        <div class="flex items-center border-r border-[#6B6A6F] sm:h-[14px] md:h-[14px] lg:h-4 xl:h-4 2xl:h-[18px]"><p class="hover:text-[#17A25F] hover:duration-300 sm:mr-7 md:mr-7 lg:mr-8 xl:mr-10 2xl:mr-10">Contactos</p></div>
        <div class="flex items-center sm:h-[14px] md:h-[14px] lg:h-4 xl:h-4 2xl:h-[18px]"><p class="hover:text-[#17A25F] hover:duration-300">Promociones</p></div>
    </div>
    <div class="flex flex-row items-center min-[320px]:pr-2 sm:pr-3 md:pr-4 lg:pr-5 xl:pr-6 2xl:pr-7">
        <%= link_to pre_login_path do%><svg class="fill-[#6B6A6F] hover:fill-[#29D884] hover:duration-700 min-[320px]:w-[18px] min-[320px]:h-[18px] min-[320px]:mr-3 sm:w-5 sm:h-5 sm:mr-4 md:w-6 md:h-6 md:mr-4 lg:w-6 lg:h-6 lg:mr-4 xl:w-6 xl:h-6 xl:mr-4 2xl:w-7 2xl:h-7 2xl:mr-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M399 384.2C376.9 345.8 335.4 320 288 320H224c-47.4 0-88.9 25.8-111 64.2c35.2 39.2 86.2 63.8 143 63.8s107.8-24.7 143-63.8zM0 256a256 256 0 1 1 512 0A256 256 0 1 1 0 256zm256 16a72 72 0 1 0 0-144 72 72 0 1 0 0 144z"/></svg><%end%>
        <a onclick="document.getElementById('Carrito').classList.remove('hidden');"><svg class="fill-[#6B6A6F] hover:fill-[#929197] hover:duration-700 min-[320px]:w-[18px] min-[320px]:h-[16px] sm:w-5 sm:h-[18px] md:w-6 md:h-[22px] lg:w-6 lg:h-[22px] xl:w-6 xl:h-[22px] 2xl:w-7 2xl:h-[26px]" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M0 24C0 10.7 10.7 0 24 0H69.5c22 0 41.5 12.8 50.6 32h411c26.3 0 45.5 25 38.6 50.4l-41 152.3c-8.5 31.4-37 53.3-69.5 53.3H170.7l5.4 28.5c2.2 11.3 12.1 19.5 23.6 19.5H488c13.3 0 24 10.7 24 24s-10.7 24-24 24H199.7c-34.6 0-64.3-24.6-70.7-58.5L77.4 54.5c-.7-3.8-4-6.5-7.9-6.5H24C10.7 48 0 37.3 0 24zM128 464a48 48 0 1 1 96 0 48 48 0 1 1 -96 0zm336-48a48 48 0 1 1 0 96 48 48 0 1 1 0-96z"/></svg></a>
    </div>
</div>

<div class="flex flex-row items-center content-center place-content-center border-b border-[#6B6A6F] border-solid min-[320px]:h-6 min-[320px]:mb-2 sm:h-[30px] sm:mb-3 md:h-[38px] md:mb-4 lg:h-[38px] lg:mb-5 xl:h-[38px] xl:mb-6 2xl:h-[42px] 2xl:mb-7">
    <div class="flex flex-row items-center content-center place-content-center group space-x-[6px]">
        <div><svg class="fill-[#ED1515] group-hover:fill-[#C80D0D] group-hover:duration-700 min-[320px]:w-2 min-[320px]:h-[10px] sm:w-3 sm:h-4 md:w-[14px] md:h-[18px] lg:w-[16px] lg:h-5 xl:w-[16px] xl:h-5 2xl:w-[18px] 2xl:h-[22px]" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M215.7 499.2C267 435 384 279.4 384 192C384 86 298 0 192 0S0 86 0 192c0 87.4 117 243 168.3 307.2c12.3 15.3 35.1 15.3 47.4 0zM192 128a64 64 0 1 1 0 128 64 64 0 1 1 0-128z"/></svg></div>
        <p class="font-ubuntu font-bold text-[#ED1515] group-hover:text-[#C80D0D] group-hover:duration-700 min-[320px]:text-[8px] sm:text-[12px] md:text-[14px] lg:text-[16px] xl:text-[18px] 2xl:text-[20px]">Ubicación</p>
        <div><svg class="fill-[#ED1515] group-hover:fill-[#C80D0D] group-hover:duration-700 min-[320px]:w-[10px] min-[320px]:h-3 sm:w-3 sm:h-4 md:w-[14px] md:h-[18px] lg:w-4 lg:h-[22px] xl:w-4 xl:h-[22px] 2xl:w-[18px] 2xl:h-[22px]" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M233.4 406.6c12.5 12.5 32.8 12.5 45.3 0l192-192c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0L256 338.7 86.6 169.4c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3l192 192z"/></svg></div>
    </div>
</div>