config/routes.rb
Rails.application.routes.draw do
  root "home#index", to: "home#index"

  get 'carts/index'

  get 'admins/index', to: 'admins#index', as: :admins

  get 'home/product_modal', to: 'home#product_modal'
  get 'home/registro', to: 'home#registro', as: :registro
  post 'home/create', to: 'home#create_registro'
  get 'home/list_products', to: 'home#list_products', as: :list_products
  get 'home/carousel', to: 'home#carousel', as: :carousel
  get 'home/pre_login', to: 'home#pre_login', as: :pre_login
  get 'home/product_modal', to: 'home#product_modal', as: :product_modal
  post 'home/product_modal', to: 'home#orden', as: :orden
  
  get 'sessions/new', to: 'sessions#new', as: :login
  post 'sessions/create', to: 'sessions#create'
  
  resources :clientes
  
  resources :tiendas
  resources :productos
  resources :usuarios


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cliente.rb
class Cliente < ApplicationRecord
    has_many :ubicacions

    validates :nombre, presence: true, length: {minimum: 4}
    validates :telefono, presence: true, length: {minimum: 10}, numericality: { only_integer: true }, uniqueness: true
    validates :contraseña, presence: true, length: { in: 8..20 }, format: { with: /\A[a-zA-Z0-9!@#$%^&*]+\z/}
    validates :condiciones, acceptance: true

    def authenticate(contraseña)
        # Lógica para verificar si la contraseña proporcionada coincide con la contraseña almacenada
        # en la base de datos para este cliente. Por ejemplo:
        self.contraseña == contraseña
    end
end

app/models/producto.rb
class Producto < ApplicationRecord
    has_one_attached :foto
    validates :nombre, presence: true
    validates :precio, presence: true
    validates :descripcion, presence: true
    validates :promocion, presence: true
    validates :tipo, presence: true
end

app/models/tienda.rb
class Tienda < ApplicationRecord
end

app/models/ubicacion.rb
class Ubicacion < ApplicationRecord
  belongs_to :cliente
end

app/models/usuario.rb
class Usuario < ApplicationRecord
    validates :nombre, presence: true, length: {minimum: 4}
    validates :nombre, format: { with: /\A[a-zA-Z]+\z/}
    validates :correo, presence: true, uniqueness: true
    validates :contraseña, presence: true, length: { in: 8..20 }, format: { with: /\A[a-zA-Z0-9!@#$%^&*]+\z/}
    validates :roll, presence: true
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
  end
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  def index
    @clientes = Cliente.all
  end

  def show
    @cliente = Cliente.find(params[:id])
  end

  def new
    @cliente = Cliente.new
  end

  def create
    @cliente = Cliente.new(cliente_params)

    if @cliente.save
        redirect_to clientes_path
    else
        render :new, status: :unprocessable_entity
    end
  end

  def edit
    @cliente = Cliente.find(params[:id])
  end

  def update
    @cliente = Cliente.find(params[:id])

    if @cliente.update(cliente_params)
        redirect_to @cliente
    else
        render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @cliente = Cliente.find(params[:id])
    @cliente.destroy

    redirect_to clientes_path, status: :see_other
  end

  private

  def cliente_params
    params.require(:cliente).permit(:nombre, :telefono, :contraseña)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # http_basic_authenticate_with name: "cascady", password: "contraseña", except: [:index]

  def index
  end
  
  def list_products

    if params[:categoria].present?
      @productos = Producto.where(tipo: params[:categoria]).with_attached_foto
    else
      @productos = Producto.all.with_attached_foto
    end

    @in = Producto.where(id: 9)
  end

  def registro
  end

  def create_registro

    @cliente = Cliente.new(cliente_params)

    if @cliente.save
        redirect_to login_path
    else
        render :registro, status: :unprocessable_entity
    end

  end

  def pre_login
  end

  def carousel
  end

  def cliente_params
    params.require(:cliente).permit(:nombre, :telefono, :contraseña, :condiciones)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
  
    def create
      @Cliente = Cliente.find_by("telefono = :telefono", { telefono: params[:telefono] })
  
      if @Cliente&.authenticate(params[:contraseña])
        redirect_to list_products_path
      else
        redirect_to new_session_path
      end
    end
  end

app/controllers/tiendas_controller.rb
class TiendasController < ApplicationController
  def index
    @tiendas = Tienda.all
  end

  def show
    @tienda = Tienda.find(params[:id])
  end

  def new
    @tienda = Tienda.new
  end

  def create
    @tienda = Tienda.new(tienda_params)

    if @tienda.save
        redirect_to tiendas_path, notice: 'Se ha agregado un nuevo tienda'
    else
        render :new, status: :unprocessable_entity
    end
  end

  def edit
    @tienda = Tienda.find(params[:id])
  end

  def update
    @tienda = Tienda.find(params[:id])

    if @tienda.update(tienda_params)
        redirect_to @tienda
    else
        render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @tienda = Tienda.find(params[:id])
    @tienda.destroy

    redirect_to tiendas_path, status: :see_other
  end

  private

  def tienda_params
    params.require(:tienda).permit(:nombre, :direccion, :telefono)
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/platillos_helper.rb
module PlatillosHelper
end

app/helpers/tiendas_helper.rb
module TiendasHelper
end

app/helpers/ubicacions_helper.rb
module UbicacionsHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/carts/index.html.erb
<div>
  <h1 class="font-bold text-4xl">Carts#index</h1>
  <p>Find me in app/views/carts/index.html.erb</p>
</div>

app/views/home/carousel.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Carousel</title>
  </head>
  <body>
      <div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <%=image_tag "Pizzas.jpg", class:"d-block w-100"%> >
          </div>
          <div class="carousel-item">
            <%=image_tag "Burgers.jpg", class:"d-block w-100"%> >
          </div>
          <div class="carousel-item">
            <%=image_tag "Sushi.jpg", class:"d-block w-100"%> >
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</html>

app/views/home/index.html.erb
<body class="bg-[#FFF1F1]">
    
    <%= render "shared/navbar1"%>
    
    <div class="bg-none min-[320px]:mx-2 sm:mx-3 md:mx-4 lg:mx-5 xl:mx-6 2xl:mx-7">
        <iframe class="w-full min-[320px]:h-[112px] sm:h-[240px] md:h-[288px] xl:h-[300px]2xl:h-[356px]" scrolling="no" src="<%=carousel_path%>" frameborder="0"></iframe>
    </div>
        <div>
            <div class="flex flex-row items-center min-[320px]:p-2 sm:p-3 md:p-4 lg:p-5">
                <p class="font-ubuntu pr-2 font-bold text-[#C80D0D] min-[320px]:text-[16px] sm:text-[20px] md:text-[24px] lg:text-[28px]">Menú</p>
                <div class="w-full"><hr class="border border-dashed border-[#C80D0D]"></div>
            </div>

            <div class="flex flex-col min-[320px]:px-2 min-[320px]:pb-2 min-[320px]:space-y-2 sm:px-3 sm:pb-3 sm:space-y-3 md:px-4 md:pb-4 md:space-y-4 lg:space-y-0 lg:grid-cols-2 lg:grid lg:px-5 lg:pb-5">
                <%= link_to list_products_path(categoria: "Hamburguesa"), data: { turbo: false } do%>
                    <div class="relative group flex place-items-center place-content-center rounded-lg  bg-cover bg-center min-[320px]:h-[96px] sm:h-[128px] md:h-[180px] lg:mr-5 lg:h-[200px]" style="background-image: url(<%= asset_path("Burgers.jpg") %>);">
                        <div class="absolute w-full bg-[rgba(0,0,0,0.5)] bg-cover h-full flex items-center place-content-center rounded-lg">
                            <p class=" text-white font-bold min-[32px]:text-[24px] min-[320px]:group-hover:text-[28px] sm:text-[32px] sm:group-hover:text-[36px] md:text-[36px] md:group-hover:text-[40px] lg:text-[40px] lg:group-hover:text-[44px]">Hamburguesas</p>
                        </div>
                    </div>
                <%end%>
                <%=link_to list_products_path(categoria: "Pizza"), data: { turbo: false } do%>
                    <div class="relative group flex place-items-center place-content-center rounded-lg  bg-cover bg-center min-[320px]:h-[96px] sm:h-[128px] md:h-[180px] lg:h-[200px]" style="background-image: url(<%= asset_path("Pizzas.jpg") %>);">
                        <div class="absolute w-full bg-[rgba(0,0,0,0.5)] bg-cover h-full flex items-center place-content-center rounded-lg">
                            <p class=" text-white font-bold min-[32px]:text-[24px] min-[320px]:group-hover:text-[28px] sm:text-[32px] sm:group-hover:text-[36px] md:text-[36px] md:group-hover:text-[40px] lg:text-[40px] lg:group-hover:text-[44px]">Pizza</p>
                        </div>
                    </div>
                <%end%>
            </div>

            <div class="flex flex-col min-[320px]:px-2 min-[320px]:pb-2 min-[320px]:space-y-2 sm:px-3 sm:pb-3 sm:space-y-3 md:px-4 md:pb-4 md:space-y-4 lg:space-y-0 lg:grid-cols-2 lg:grid lg:px-5 lg:pb-5">
                <%=link_to list_products_path(categoria: "Shusi"), data: { turbo: false } do%>
                    <div class="relative group flex place-items-center place-content-center rounded-lg  bg-cover bg-center min-[320px]:h-[96px] sm:h-[128px] md:h-[180px] lg:mr-5 lg:h-[200px]" style="background-image: url(<%= asset_path("Sushi.jpg") %>);">
                        <div class="absolute w-full bg-[rgba(0,0,0,0.5)] bg-cover h-full flex items-center place-content-center rounded-lg">
                            <p class=" text-white font-bold min-[32px]:text-[24px] min-[320px]:group-hover:text-[28px] sm:text-[32px] sm:group-hover:text-[36px] md:text-[36px] md:group-hover:text-[40px] lg:text-[40px] lg:group-hover:text-[44px]">Sushi</p>
                        </div>
                    </div>
                <%end%>
                <%=link_to list_products_path(categoria: "Alitas"), data: { turbo: false } do%>
                    <div class="relative group flex place-items-center place-content-center rounded-lg  bg-cover bg-center min-[320px]:h-[96px] sm:h-[128px] md:h-[180px] lg:h-[200px]" style="background-image: url(<%= asset_path("Alitas.jpg") %>);">
                        <div class="absolute w-full bg-[rgba(0,0,0,0.5)] bg-cover h-full flex items-center place-content-center rounded-lg">
                            <p class=" text-white font-bold min-[32px]:text-[24px] min-[320px]:group-hover:text-[28px] sm:text-[32px] sm:group-hover:text-[36px] md:text-[36px] md:group-hover:text-[40px] lg:text-[40px] lg:group-hover:text-[44px]">Alitas</p>
                        </div>
                    </div>
                <%end%>
            </div>

        </div>
</body>

<%= render "shared/footer"%>

app/views/home/pre_login.html.erb
<body class="bg-cover bg-center h-screen" style="background-image: url('<%=asset_path("pre_login.jpg")  %>');">

    <%= render "shared/navbar2"%>

    <div class="flex place-content-center place-items-center">
        <div class="bg-white drop-shadow-2xl rounded-lg w-full min-[320px]:my-[32px] min-[320px]:mx-6 sm:my-[48px] sm:mx-[96px] md:mx-[128px] md:my-[64px] lg:mx-[160px] lg:my-[80px] xl:mx-[192px] 2xl:mx-[224px]">
            <div class="text-center min-[320px]:mt-3 min-[320px]:mb-4 sm:mt-[18px] sm:mb-6 md:mt-6 md:mb-8 lg:mt-[30px] lg:mb-10 xl:mt-[36px] xl:mb-[48px] 2xl:mt-[42px] 2xl:mb-[56px]">
                <p class="font-ubuntu font-bold min-[320px]:text-[14px] sm:text-[18px] md:text-[20px] lg:text-[22px] xl:text-[24px] 2xl:text-[28px]">Regístrate o inicia sesión</p>
            </div>
            <div class="flex flex-col justify-center min-[320px]:space-y-2 min-[320px]:mb-8 sm:space-y-3 sm:mb-[48px] md:space-y-4 md:mb-[64px] lg:space-y-5 lg:mb-20 xl:space-y-6 xl:mb-[96px]">
                <button class="flex flex-row justify-center place-content-center place-items-center bg-[#881414] hover:bg-[#4B0404] hover:duration-100 rounded-[24px] min-[320px]:h-[28px] min-[320px]:mx-10 sm:h-[36px] sm:mx-[48px] md:h-10 md:mx-[64px] lg:h-11 lg:mx-[80px] xl:h-12 xl:mx-[96px] 2xl:h-[52px] 2xl:mx-[112px]">
                    <%=image_tag "google.png", class:"mr-2 min-[320px]:w-[16px] min-[320px]:h-[16px] sm:w-[20px] sm:h-[20px] xl:w-6 xl:h-6 2xl:w-7 2xl:h-7",  alt:"google"%>
                    <p class="font-ubuntu font-normal text-white min-[320px]:text-[12px] sm:text-[18px] lg:text-[20px] xl:text-[22px] 2xl:text-[24px]">Continuar con Google</p>
                </button>

                <button class="flex flex-row justify-center place-content-center place-items-center bg-[#172CB6] hover:bg-[#192B8F] hover:duration-100 rounded-[24px] min-[320px]:h-[28px] min-[320px]:mx-10 sm:h-[36px] sm:mx-[48px] md:h-10 md:mx-[64px] lg:h-11 lg:mx-[80px] xl:h-12 xl:mx-[96px] 2xl:h-[52px] 2xl:mx-[112px]">
                    <svg class="mr-2 min-[320px]:w-[16px] min-[320px]:h-[16px] sm:w-[20px] sm:h-[20px] xl:w-6 xl:h-6 2xl:w-7 2xl:h-7" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path fill="#ffffff" d="M512 256C512 114.6 397.4 0 256 0S0 114.6 0 256C0 376 82.7 476.8 194.2 504.5V334.2H141.4V256h52.8V222.3c0-87.1 39.4-127.5 125-127.5c16.2 0 44.2 3.2 55.7 6.4V172c-6-.6-16.5-1-29.6-1c-42 0-58.2 15.9-58.2 57.2V256h83.6l-14.4 78.2H287V510.1C413.8 494.8 512 386.9 512 256h0z"/></svg>
                    <p class="font-ubuntu font-normal text-white min-[320px]:text-[12px] sm:text-[18px] lg:text-[20px] xl:text-[22px] 2xl:text-[24px]">Continuar con Facebook</p>
                </button>

                <a href="<%=registro_path%>" class="flex justify-center place-content-center place-items-center bg-[#29D884] hover:bg-[#17A25F] hover:duration-100 rounded-[24px] min-[320px]:h-[28px] min-[320px]:mx-10 sm:h-[36px] sm:mx-[48px] md:h-10 md:mx-[64px] lg:h-11 lg:mx-[80px] xl:h-12 xl:mx-[96px] 2xl:h-[52px] 2xl:mx-[112px] font-ubuntu font-normal text-white min-[320px]:text-[12px] sm:text-[18px] lg:text-[20px] xl:text-[22px] 2xl:text-[24px]">
                    <svg class="mr-2 min-[320px]:w-[16px] min-[320px]:h-[16px] sm:w-[20px] sm:h-[20px] xl:w-6 xl:h-6 2xl:w-7 2xl:h-7" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path fill="#ffffff" d="M164.9 24.6c-7.7-18.6-28-28.5-47.4-23.2l-88 24C12.1 30.2 0 46 0 64C0 311.4 200.6 512 448 512c18 0 33.8-12.1 38.6-29.5l24-88c5.3-19.4-4.6-39.7-23.2-47.4l-96-40c-16.3-6.8-35.2-2.1-46.3 11.6L304.7 368C234.3 334.7 177.3 277.7 144 207.3L193.3 167c13.7-11.2 18.4-30 11.6-46.3l-40-96z"/></svg>
                    Continuar con tu celular
                </a>
                <a href="<%=login_path%>" class="flex justify-center place-content-center place-items-center bg-transparent border-[#17A25F] border-2 border-solid hover:bg-[#DCFCEC] hover:duration-100 rounded-[24px] min-[320px]:h-[28px] min-[320px]:mx-10 sm:h-[36px] sm:mx-[48px] md:h-10 md:mx-[64px] lg:h-11 lg:mx-[80px] xl:h-12 xl:mx-[96px] 2xl:h-[52px] 2xl:mx-[112px] font-ubuntu font-normal text-[#17A25F] min-[320px]:text-[12px] sm:text-[18px] lg:text-[20px] xl:text-[22px] 2xl:text-[24px]">
                    Ya tengo una cuenta
                </a>
            </div>
        </div>
    </div>
</body>

app/views/home/registro.html.erb
<body>
    
    <%= render "shared/navbar2"%>

    <div class="lg:grid lg:grid-cols-12 h-screen">
        <div class="relative bg-cover bg-center min-[320px]:hidden lg:flex lg:col-span-5" style="background-image: url('<%=asset_path("registro.jpg")  %>');">
            <p class="absolute bg-[rgba(0,0,0,0.5)] bg-cover h-full items-start flex place-self-center place-content-center w-full text-center font-ubuntu font-bold pt-[173px] text-white lg:text-[48px] 2xl:text-[52px]">¡Únete a nosotros y disfruta de nuestras ofertas!</p>
        </div>
        <div class="flex flex-col lg:col-span-7">
            <div class="flex place-content-center place-items-center min-[320px]:mt-6 min-[320px]:mb-4 sm:mt-9 sm:mb-6 md:mt-12 md:mb-8">
                <p class="font-ubuntu font-bold min-[320px]:text-[16px] sm:text-[20px] md:text-[22px] lg:text-[24px] 2xl:text-[28px]">Regístrate</p>
            </div>
            <%= form_with model: @cliente, url: home_create_path do |form| %>
                <div class="flex flex-col min-[320px]:mx-[40px] min-[320px]:space-y-4 min-[320px]:mb-4 sm:mx-[110px] sm:space-y-6 sm:mb-6 md:mx-[160px] md:mb-8 lg:mx-16 xl:mx-[106px] 2xl:mx-[128px]">
                    <%= form.text_field :nombre, class:"bg-[#F5F5F5] rounded drop-shadow px-2 font-ubuntu font-light text-[#6B6A6F] focus:outline-none min-[320px]:text-[10px] min-[320px]:h-6 sm:h-[30px] sm:text-[14px] md:h-9 xl:h-10 xl:text-[16px] 2xl:h-11 2xl:text-[18px]", placeholder:"Nombre"%>
                    <%= form.text_field :telefono, class:"bg-[#F5F5F5] rounded drop-shadow px-2 font-ubuntu font-light text-[#6B6A6F] focus:outline-none min-[320px]:text-[10px] min-[320px]:h-6 sm:h-[30px] sm:text-[14px] md:h-9 xl:h-10 xl:text-[16px] 2xl:h-11 2xl:text-[18px]", placeholder:"Número de teléfono"%>
                    <div class="flex flex-col space-y-1">
                        <%= form.password_field :contraseña, class:"bg-[#F5F5F5] rounded drop-shadow px-2 font-ubuntu font-light text-[#6B6A6F] focus:outline-none min-[320px]:text-[10px] min-[320px]:h-6 sm:h-[30px] sm:text-[14px] md:h-9 xl:h-10 xl:text-[16px] 2xl:h-11 2xl:text-[18px]", placeholder:"Ingresar tu contraseña"%>
                        <div class="flex flex-row items-center space-x-1">
                            <svg class="min-[320px]:w-[6px] min-[320px]:h-[6px] sm:w-3 sm:h-3 xl:w-[14px] xl:h-[14px] 2xl:w-4 2xl:h-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path fill="#6b6a6f" d="M64 32C28.7 32 0 60.7 0 96V416c0 35.3 28.7 64 64 64H384c35.3 0 64-28.7 64-64V96c0-35.3-28.7-64-64-64H64zM337 209L209 337c-9.4 9.4-24.6 9.4-33.9 0l-64-64c-9.4-9.4-9.4-24.6 0-33.9s24.6-9.4 33.9 0l47 47L303 175c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9z"/></svg>
                            <p class="font-ubuntu font-light text-[#6B6A6F] min-[320px]:text-[6px] sm:text-[12px] xl:text-[14px] 2xl:text-[16px]">La contraseña debe tener entre 8 a 16 caracteres</p>
                        </div>
                        <div class="flex flex-row items-center space-x-1">
                            <svg class="min-[320px]:w-[6px] min-[320px]:h-[6px] sm:w-3 sm:h-3 xl:w-[14px] xl:h-[14px] 2xl:w-4 2xl:h-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path fill="#6b6a6f" d="M64 32C28.7 32 0 60.7 0 96V416c0 35.3 28.7 64 64 64H384c35.3 0 64-28.7 64-64V96c0-35.3-28.7-64-64-64H64zM337 209L209 337c-9.4 9.4-24.6 9.4-33.9 0l-64-64c-9.4-9.4-9.4-24.6 0-33.9s24.6-9.4 33.9 0l47 47L303 175c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9z"/></svg>
                            <p class="font-ubuntu font-light text-[#6B6A6F] min-[320px]:text-[6px] sm:text-[12px] xl:text-[14px] 2xl:text-[16px]">La contraseña debe de contener minimo dos símbolos o números</p>
                        </div>
                    </div>
                    
                    <%= form.password_field :validacion, class:"bg-[#F5F5F5] rounded drop-shadow px-2 font-ubuntu font-light text-[#6B6A6F] focus:outline-none min-[320px]:text-[10px] min-[320px]:h-6 sm:h-[30px] sm:text-[14px] md:h-9 xl:h-10 xl:text-[16px] 2xl:h-11 2xl:text-[18px]", placeholder:"Vuelve a ingresar tu contraseña" %>

                    <div class="flex flex-row space-x-1 items-center">
                        <%= form.check_box :condiciones, class:"min-[320px]:w-2 min-[320px]:h-2 sm:w-[14px] sm:h-[14px] 2xl:h-4"%>
                        <p class="font-ubuntu font-normal min-[320px]:text-[8px] sm:text-[10px] xl:text-[12px] 2xl:text-[14px]">Acepto</p>
                        <a href="#"><p class="font-ubuntu font-normal italic text-[#1436E1] min-[320px]:text-[8px] sm:text-[10px] xl:text-[12px] 2xl:text-[14px]">Términos de uso y política de privacidad</p></a>
                    </div>

                    <button class="bg-[#FF1F1F] rounded hover:bg-[#ED1515] min-[320px]:h-6 sm:h-[30px] md:h-9 xl:h-10 2xl:h-11">
                        <%= form.submit "Siguiente", class:"font-ubuntu font-bold text-white min-[320px]:text-[12px] sm:text-[14px] xl:text-[16px] 2xl:text-[18px]" %>
                    </button>
                </div>
            <%end%>
            <div class="flex place-content-center place-items-center space-x-1">
                <p class="font-ubuntu font-light min-[320px]:text-[8px] sm:text-[12px] xl:text-[14px]">Ya tienes una cuenta?</p>
                <a href="<%=login_path%>"><p class="font-ubuntu font-light text-[#FF1F1F] min-[320px]:text-[8px] sm:text-[12px] xl:text-[14px]">Inica sesión</p></a>
            </div>
        </div>
    </div>
</body>